version: "2"

services:
    drupal:
        image: drupal:7-apache
        restart: always
        volumes:
          - "/var/log/apache2/abc:/var/log/apache2"
          - "./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
          - /var/www/html/
          - "./code/sites/default/docker.settings.php:/var/www/html/sites/default/settings.php"
          - "./code/sites/all:/var/www/html/sites/all"
          - "./code/sites/default/files:/var/www/html/sites/default/files:rw"
        # links:
        #   - db:mysql
        network_mode: "bridge"
        external_links:
          - db_mysql_1:mysql
        # networks:
        #   - db_net
        #https://notes.wanghao.work/2017-06-12-Docker-Compose-%E9%93%BE%E6%8E%A5%E5%A4%96%E9%83%A8%E5%AE%B9%E5%99%A8%E7%9A%84%E5%87%A0%E7%A7%8D%E6%96%B9%E5%BC%8F.html
        environment:
          - VIRTUAL_HOST=wx.yongbuzhixi.com
          - LETSENCRYPT_HOST=wx.yongbuzhixi.com
          - LETSENCRYPT_EMAIL=dale.tel@139.com
    # db:
    #   image: mariadb
    #   restart: always
    #   network_mode: "bridge"
    #   volumes:
    #     - "./sql:/sql"
    #     - "./sql/data:/var/lib/mysql"
    #   environment:
    #     - MYSQL_USER=drupal
    #     - MYSQL_PASSWORD=drupal
    #     - MYSQL_DATABASE=drupal
    #     - MYSQL_ROOT_PASSWORD=drupal
# networks:
#   db_net:
#     external: true