version: "2"

services:
    drupal:
        image: drupal:7-apache
        restart: always
        network_mode: "bridge"
        volumes:
          - "/var/log/apache2/abc:/var/log/apache2"
          - "./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
          - /var/www/html/
          - "./code/sites/default/docker.settings.php:/var/www/html/sites/default/settings.php"
          - "./code/sites/all:/var/www/html/sites/all"
          - "./code/sites/default/files:/var/www/html/sites/default/files:rw"
        links:
          - db:mysql
        environment:
          - VIRTUAL_HOST=wx.yongbuzhixi.com
          - LETSENCRYPT_HOST=wx.yongbuzhixi.com
          - LETSENCRYPT_EMAIL=dale.tel@139.com
    db:
      image: mariadb
      restart: always
      network_mode: "bridge"
      volumes:
        - "./sql:/sql"
        - "./sql/data:/var/lib/mysql"
      environment:
        - MYSQL_USER=drupal
        - MYSQL_PASSWORD=drupal
        - MYSQL_DATABASE=drupal
        - MYSQL_ROOT_PASSWORD=drupal