version: "2"

services:
    web:
        image: nginx:latest
        restart: always
        network_mode: "bridge"
        volumes:
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            #- ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/drupal.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/amplify.conf:/etc/nginx/conf.d/amplify.conf
        volumes_from:
          - php
        links:
          - php
        environment:
          - VIRTUAL_HOST=wx.yongbuzhixi.com
          - LETSENCRYPT_HOST=wx.yongbuzhixi.com
          - LETSENCRYPT_EMAIL=dale.tel@139.com
    
    #api-code-app > drupal:fpm > php:7-fpm 只执行一次！！！
    php:
        image: drupal:7-fpm
        # image: drupal-php7-fpm #给build镜像后的image命名
        restart: always
        network_mode: "bridge"
        # volumes_from:
        #   - storage-drupal
        volumes:
          # - '/var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock:ro'
          # - '/usr/local/bin/drush.phar:/usr/local/bin/drush.phar:ro'
          - "./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf:ro"
          # - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
          - ./conf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
          # - /var/www/html/sites/default
          - "./code:/var/www/html"
          - "./code/sites/default/settings.php:/var/www/html/sites/default/settings.php:rw"
          # - "./code/modules:/var/www/html/modules:ro"
          # - "./code/themes:/var/www/html/themes:ro"
          # - "./code/libraries:/var/www/html/libraries:ro"
          - "./code/sites/default/files:/var/www/html/sites/default/files:rw"